	
var siteData ={
	"imgData":{
		"img1":{ "img":"img/White-&-Blue-Hearts-014.jpg" , "imgAlt":"white and blue hearts image", "header":"white Neon Heart Box ", "content":"White Neon 8inch wide 6inch tall.Upcycled timber Box. Overall  size is white 11inch wide 8.5inch tallOriginal concept by Sadie Frost.","price":"£420","imageHeight":["100%","100%"],"imageWidth":["100%","100%"], "contentImg":["img/White-&-Blue-Hearts-014.jpg", "img/White-&-Blue-Hearts-018.jpg"],"actionInfo":["https://www.paypal.com/cgi-bin/webscr"],"method":["post"],"target":["_top"],"type":["hidden"],"name1":["cmd"],"value1":["_s-xclick"],"name2":["hosted_button_id"],"value2":["T9FV8P5D7Q8A6"], },
		"img2":{ "img":"img/Warhol's Banana.jpg" , "imgAlt":"warhol's Banana", "header":"Warhol's Banana", "content":"32Inch wide 16Inch tall.Soft White LED light bulbs.Matt Black faced with textured Diamante.One of four  pieces we created as part of an exhibition for CentrePoint UK. Dean St, Soho, London.","price":"£360","imageHeight":["100%"],"imageWidth":["100%"], "contentImg":["img/Warhol's Banana.jpg"],"actionInfo":["https://www.paypal.com/cgi-bin/webscr"],"method":["post"],"target":["_top"],"type":["hidden"],"name1":["cmd"],"value1":["_s-xclick"],"name2":["hosted_button_id"],"value2":["834LGW7GLCJTS"]},	
		"img3":{ "img":"img/You-make-you-feel-Good_1.jpg" , "imgAlt":"you make me feel good", "header":"You Make Me Feel Good", "content":"Electric Blue Neon Scripted Typography.Neon letters are 4inch tall.Overall size is 1.5 mts long 1.1 mts tall.One of four pieces we created as part of an exhibition for CentrePoint UK. Dean St, Soho, London.","price":"£980","imageHeight":["100%","100%"],"imageWidth":["100%","100%"], "contentImg":["img/You-make-you-feel-Good_1.jpg","img/You-make-you-feel-Good_2.jpg"],"actionInfo":["https://www.paypal.com/cgi-bin/webscr"],"method":["post"],"target":["_top"],"type":["hidden"],"name1":["cmd"],"value1":["_s-xclick"],"name2":["hosted_button_id"],"value2":["7JYRAFTWBL7XQ"]},	
		
		"img4":{ "img":"img/redHeart.jpg" , "imgAlt":"red heart", "header":"Pink Neon Heart ", "content":"Bright Pink Neon 8 Inch's wide 6 Inch's tall.White Box  with Matt Black interior.Overall  size is white 11Inch wide 8.5Inch tall Original concept  by  Sadie Frost.","imageHeight":["100%","100%"],"price":"£420","imageWidth":["100%","100%"], "contentImg":["img/pinkBox1.jpg", "img/pinkBox2.jpg"],"actionInfo":["https://www.paypal.com/cgi-bin/webscr"],"method":["post"],"target":["_top"],"type":["hidden"],"name1":["cmd"],"value1":["_s-xclick"],"name2":["hosted_button_id"],"value2":["GLPSJDR8W62W8"] },
		"img5":{ "img":"img/I-Want-to-Kiss-You.jpg" , "imgAlt":"i want to kiss", "header":"I Want to Kiss You", "content":"'Up-Cycled' Road Works Sign on Pink Neon Type.Neon letters are 3Inch tall.Overall size is 700mm X 700mm.One of four  pieces we created as part of an exhibition for CentrePoint UK. Dean St, Soho, London.","price":"£960","imageHeight":["100%","100%"],"imageWidth":["100%","100%"], "contentImg":["img/I-Want-to-Kiss-You.jpg", "img/I-Want-to-Kiss-You-Detail.jpg"],"actionInfo":["https://www.paypal.com/cgi-bin/webscr"],"method":["post"],"target":["_top"],"type":["hidden"],"name1":["cmd"],"value1":["_s-xclick"],"name2":["hosted_button_id"],"value2":["9WQ57KXJU284J"] },
		

		"img6":{ "img":"img/Purple-Heart-E-003.jpg" , "imgAlt":"purple heart", "header":"Purple Neon Heart in a Box", "content":"Purple  Neon  8Inch's wide 6Inch's tall.Matt Black Box with Matt Black interior.Overall  size is white 11Inch's wide 8.5Inch's tall Original concept  by  Sadie Frost.","price":"check out our contact section to get a quote","imageHeight":["100%"],"imageWidth":["100%","100%"], "contentImg":["img/Purple-Heart-E-003.jpg","img/Purple-Heart-E-009.jpg", "img/Purple-Heart-E-021.jpg"],"actionInfo":["https://www.paypal.com/cgi-bin/webscr"],"method":["post"],"target":["_top"],"type":["hidden"],"name1":["cmd"],"value1":["_s-xclick"],"name2":["hosted_button_id"],"value2":["SEXXXXXXXXXX"]},
		"img7":{ "img":"img/Sometimes-its-a-Yes_3.jpg" , "imgAlt":"Sometimes its a Yes", "header":"Sometimes it's a Yes", "content":"10inch wide 27inch high Light Box Polished Steel sides.White Acrylic with Black Vinyl Graphic.One of four pieces we created as part of an exhibition for CentrePoint UK. Dean St, Soho, London.","price":["£460"],"imageHeight":["100%"],"imageHeight":["100%"],"imageWidth":["40%","40%"], "contentImg":["img/Sometimes-its-a-Yes_2.jpg", "img/Sometimes-its-a-Yes_3.jpg"],"actionInfo":["https://www.paypal.com/cgi-bin/webscr"],"method":["post"],"target":["_top"],"type":["hidden"],"name1":["cmd"],"value1":["_s-xclick"],"name2":["hosted_button_id"],"value2":["8FUFBWHQZE8B8"]},
		
		"img8":{ "img":"img/There-is-Enough-Love_1.jpg" , "imgAlt":"there Enough Love", "header":"Enough Love for Everyone", "content":"60 cm Circular Yellow light box with Orange 60's style type.","imageHeight":["100%"],"imageWidth":["80%","80%"], "contentImg":["img/There-is-Enough-Love_1.jpg","img/There-is-Enough-Love_2.jpg"],"price":"£550","actionInfo":["https://www.paypal.com/cgi-bin/webscr"],"method":["post"],"target":["_top"],"type":["hidden"],"name1":["cmd"],"value1":["_s-xclick"],"name2":["hosted_button_id"],"value2":["EQULPZLHFM2SG"]},
		"img9":{ "img":"img/Yellow-Star-029.jpg","imgAlt": "gold Neon Star","header": "Gold Neon Star in a Box","content": "Gold  Neon  6inch wide 6inch tall.Black Box with Matt Black Textured interior.Overall size is white 11inch wide 11inch tall Based on original concept by Sadie Frost.","price":"£440","imageHeight":["100%"],"imageWidth": ["100%","100%"],"contentImg": ["img/Yellow-Star-023.jpg","img/Yellow-Star-029.jpg"],"actionInfo":["https://www.paypal.com/cgi-bin/webscr"],"method":["post"],"target":["_top"],"type":["hidden"],"name1":["cmd"],"value1":["_s-xclick"],"name2":["hosted_button_id"],"value2":["V7LU7HPU2F4JW"] },
		
		"img10":{ "img":"img/White-&-Blue-Hearts-007.jpg" , "imgAlt":"Blue Neon Heart in a Box", "header":"Blue Neon Heart in a Box", "content":"Electric Blue Neon 8Inch's wide 6Inch's tall.Matt Black Box with Matt Black interior.Overall  size is white 11Inch's wide 8.5Inch's tall Original concept by Sadie Frost.","price":"£420","imageHeight":["100%"],"imageWidth":["100%","100%"], "contentImg":["img/White-&-Blue-Hearts-004.jpg", "img/White-&-Blue-Hearts-007.jpg"],"actionInfo":["https://www.paypal.com/cgi-bin/webscr"],"method":["post"],"target":["_top"],"type":["hidden"],"name1":["cmd"],"value1":["_s-xclick"],"name2":["hosted_button_id"],"value2":["4F43RV7X2PF3U"] },
	}
	
};	